# Generated by Django 3.1.10 on 2021-05-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='course_id',
            new_name='branch_id',
        ),
    ]
