# Generated by Django 3.1.12 on 2021-06-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_login_details',
        ),
    ]
