# Generated by Django 3.1.12 on 2021-10-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login_details',
            name='latitude',
            field=models.CharField(default='5', max_length=100),
        ),
        migrations.AddField(
            model_name='user_login_details',
            name='longitude',
            field=models.CharField(default='5', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_social_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncl_app.staffs'),
        ),
        migrations.AlterField(
            model_name='student_course_reg',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncl_app.staffs'),
        ),
        migrations.AlterField(
            model_name='student_social_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncl_app.students'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='staff_id',
            field=models.ManyToManyField(to='oncl_app.Staffs'),
        ),
    ]
