# Generated by Django 3.1.7 on 2021-04-17 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oncl_app', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCS_Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('topics', models.TextField(blank=True, max_length=200, null=True)),
                ('url', models.TextField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('faculty_name', models.CharField(max_length=200)),
                ('faculty_email', models.CharField(max_length=200)),
                ('faculty_phno', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'user',
            },
        ),
    ]
