# Generated by Django 3.1.12 on 2021-07-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0003_user_login_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login_details',
            name='device_name',
        ),
    ]
