# Generated by Django 3.1.10 on 2021-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0006_staffs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='admin',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
