# Generated by Django 3.1.10 on 2021-05-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0008_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_file', models.FileField(upload_to='exams/')),
                ('marks', models.IntegerField(default=0)),
                ('branch_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oncl_app.branches')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncl_app.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oncl_app.subjects')),
            ],
        ),
    ]
