# Generated by Django 3.1.10 on 2021-05-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0009_auto_20210512_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
