# Generated by Django 3.1.10 on 2021-05-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0010_auto_20210518_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_sub', models.CharField(max_length=50)),
                ('exam_file', models.FileField(upload_to='answers/')),
                ('exam_marks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncl_app.students')),
            ],
        ),
    ]
