# Generated by Django 3.1.10 on 2021-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0011_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='course_id',
            new_name='branch_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='session_year_id',
            new_name='semester_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
