# Generated by Django 3.1.10 on 2021-05-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0011_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_ques',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_file', models.FileField(upload_to='question/')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oncl_app.subjects')),
            ],
        ),
    ]
