# Generated by Django 3.1.10 on 2021-05-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0012_exam_ques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_file',
            new_name='ans_file',
        ),
    ]
