# Generated by Django 3.1.10 on 2021-05-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0012_auto_20210512_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='semester_id',
        ),
    ]
