# Generated by Django 3.1.10 on 2021-05-18 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0013_auto_20210518_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClassRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('room_pwd', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncl_app.staffs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncl_app.subjects')),
            ],
        ),
    ]
