# Generated by Django 3.1.10 on 2021-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0014_attendance_attendancereport_leavereportstaff_leavereportstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements_news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('announcements_news', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
