# Generated by Django 3.1.10 on 2021-05-19 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0014_onlineclassroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReportStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.CharField(max_length=50)),
                ('subject_id', models.CharField(max_length=50)),
                ('attend_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncl_app.students')),
            ],
        ),
    ]
