# Generated by Django 3.1.10 on 2021-05-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0015_attendancereportstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereportstudent',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
