# Generated by Django 3.1.10 on 2021-05-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0015_announcements_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements_news',
            old_name='announcements_news',
            new_name='what_an',
        ),
    ]
