# Generated by Django 3.1.10 on 2021-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0016_auto_20210512_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='branch',
            field=models.CharField(default='', max_length=255),
        ),
    ]
