# Generated by Django 3.1.10 on 2021-05-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0017_auto_20210519_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereportstudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
