# Generated by Django 3.1.10 on 2021-05-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0017_students_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
