# Generated by Django 3.1.10 on 2021-05-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0018_auto_20210512_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('my_file', models.FileField(upload_to='books/')),
            ],
        ),
    ]
