# Generated by Django 3.1.10 on 2021-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0019_auto_20210519_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereportstudent',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
