# Generated by Django 3.1.10 on 2021-05-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0020_staffs_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bio',
            field=models.TextField(default='Not Updated Yet!'),
        ),
        migrations.AddField(
            model_name='students',
            name='git_link',
            field=models.TextField(default='Not Updated Yet!'),
        ),
        migrations.AddField(
            model_name='students',
            name='linkedin_link',
            field=models.TextField(default='Not Updated Yet!'),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.TextField(default='Not Updated Yet!'),
        ),
        migrations.AddField(
            model_name='students',
            name='twitter_link',
            field=models.TextField(default='Not Updated Yet!'),
        ),
        migrations.AddField(
            model_name='students',
            name='website_link',
            field=models.TextField(default='Not Updated Yet!'),
        ),
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(default='Not Updated Yet!'),
        ),
    ]
