# Generated by Django 3.1.10 on 2021-05-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0021_auto_20210513_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.CharField(default='Not Updated Yet!', max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
    ]
