# Generated by Django 3.1.10 on 2021-05-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0023_students_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload',
            old_name='my_file',
            new_name='book_file',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='fname',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_author',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_desc',
            field=models.CharField(default='Not Updated Yet!', max_length=255),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_name',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
