# Generated by Django 3.1.10 on 2021-05-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0024_auto_20210513_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='book_id',
            field=models.CharField(default='Not Updated Yet!', max_length=100),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_pub_date',
            field=models.CharField(default='Not Updated Yet!', max_length=20),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_tag1',
            field=models.CharField(default='Not Updated Yet!', max_length=20),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_tag2',
            field=models.CharField(default='Not Updated Yet!', max_length=20),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_tag3',
            field=models.CharField(default='Not Updated Yet!', max_length=20),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='book_tag4',
            field=models.CharField(default='Not Updated Yet!', max_length=20),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_desc',
            field=models.CharField(default='Not Updated Yet!', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.CharField(default='Not Updated Yet!', max_length=100),
        ),
    ]
