# Generated by Django 3.1.10 on 2021-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0026_auto_20210513_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='book_desc',
            field=models.TextField(default='Not Updated Yet!', max_length=255),
        ),
    ]
