# Generated by Django 3.1.10 on 2021-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0027_auto_20210513_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements_news',
            name='sub_an',
            field=models.CharField(default='Subject Not Provided!', max_length=100),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_author',
            field=models.CharField(default='Not ProvidedYet!', max_length=50),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_desc',
            field=models.TextField(default='Not ProvidedYet!', max_length=255),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_id',
            field=models.CharField(default='Not ProvidedYet!', max_length=100),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_name',
            field=models.CharField(default='Not ProvidedYet!', max_length=50),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_pub_date',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_tag1',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_tag2',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_tag3',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_tag4',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
    ]
