# Generated by Django 3.1.10 on 2021-05-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0028_auto_20210513_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar.webp', null=True, upload_to=''),
        ),
    ]
