# Generated by Django 3.1.10 on 2021-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0029_auto_20210514_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_author',
            field=models.CharField(default='Not ProvidedYet!', max_length=50),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_desc',
            field=models.TextField(default='Not ProvidedYet!', max_length=255),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_file',
            field=models.FileField(default='', upload_to='sessions/'),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_id',
            field=models.CharField(default='Not ProvidedYet!', max_length=100),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_name',
            field=models.CharField(default='Not ProvidedYet!', max_length=50),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_pic',
            field=models.ImageField(blank=True, default='session_default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_pub_date',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_tag1',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_tag2',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_tag3',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AddField(
            model_name='pcs_cloud',
            name='session_tag4',
            field=models.CharField(default='Not ProvidedYet!', max_length=20),
        ),
        migrations.AlterField(
            model_name='pcs_cloud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterOrderWithRespectTo(
            name='pcs_cloud',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='pcs_cloud',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='pcs_cloud',
            name='faculty_email',
        ),
        migrations.RemoveField(
            model_name='pcs_cloud',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='pcs_cloud',
            name='faculty_phno',
        ),
        migrations.RemoveField(
            model_name='pcs_cloud',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pcs_cloud',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='pcs_cloud',
            name='url',
        ),
        migrations.RemoveField(
            model_name='pcs_cloud',
            name='user',
        ),
    ]
