# Generated by Django 3.1.10 on 2021-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0030_auto_20210514_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branch_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='book_pic',
            field=models.ImageField(blank=True, default='book.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pcs_cloud',
            name='session_pic',
            field=models.ImageField(blank=True, default='session.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='git_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='linkedin_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='twitter_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='website_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
