# Generated by Django 3.1.10 on 2021-05-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0031_auto_20210514_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='twitter_link',
        ),
    ]
