# Generated by Django 3.1.10 on 2021-05-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0032_remove_students_twitter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
