# Generated by Django 3.1.10 on 2021-05-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0033_auto_20210515_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='bio',
            field=models.TextField(default='Not Updated Yet!'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='git_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='linkedin_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='website_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
    ]
