# Generated by Django 3.1.10 on 2021-05-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0034_auto_20210515_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='gscholar_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='microsoft_academic_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='orcid_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='qualification',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='researcher_link',
            field=models.CharField(default='Not Updated Yet!', max_length=50),
        ),
    ]
