# Generated by Django 3.1.10 on 2021-05-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0035_auto_20210515_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='profile_image',
            new_name='profile_pic',
        ),
    ]
