# Generated by Django 3.1.10 on 2021-05-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0037_auto_20210515_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='book_pic',
            field=models.ImageField(blank=True, default='book.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pcs_cloud',
            name='session_pic',
            field=models.ImageField(blank=True, default='session.jpg', null=True, upload_to=''),
        ),
    ]
