# Generated by Django 3.1.10 on 2021-05-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0039_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gender',
            new_name='Gender_model',
        ),
    ]
