# Generated by Django 3.1.10 on 2021-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0040_auto_20210515_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender_model',
            name='female',
        ),
        migrations.RemoveField(
            model_name='gender_model',
            name='male',
        ),
        migrations.AddField(
            model_name='gender_model',
            name='gender',
            field=models.CharField(default='', max_length=11),
        ),
    ]
