# Generated by Django 3.1.10 on 2021-05-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncl_app', '0041_auto_20210515_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='branch_name',
            new_name='branch',
        ),
    ]
